name: CLI Tests

on: 
  push:
    paths:
      - '**cli**'
  pull_request:
    paths:
      - '**cli**'

jobs:
  test-latest:
    name: foss_cli tests (latest Fossology)
    runs-on: ubuntu-latest

    container:
      image: python:3.10-slim
      volumes:
        - /tmp:/tmp

    services:
      fossology:
        image: fossology/fossology:latest
        ports:
          - 8081:80
        volumes:
          - /tmp:/tmp

    steps:
      - uses: actions/checkout@v1
      - name: Install host dependencies
        run: |
          apt-get -qq update
          apt-get install -qq gcc git nmap xz-utils
          rm -rf /var/lib/apt/lists/*
      - name: Install Python dependencies
        run: |
          pip install poetry
          poetry install
      - name: Install files in shared volume
        run: |
          tar xJf tests/files/base-files_11.tar.xz -C /tmp
      - name: Check services
        run: nmap fossology -p 80
      - name: Run tests
        run: |
          poetry run coverage run --source=fossology -m pytest tests/test_foss_cli*.py
          poetry run coverage report -m
 
  test-last_release:
    name: foss_cli tests (Fossology 4.1.0)
    runs-on: ubuntu-latest

    container:
      image: python:3.10-slim
      volumes:
        - /tmp:/tmp

    services:
      fossology:
        image: fossology/fossology:4.1.0
        ports:
          - 8081:80
        volumes:
          - /tmp:/tmp

    steps:
      - uses: actions/checkout@v1
      - name: Install host dependencies
        run: |
          apt-get -qq update
          apt-get install -qq gcc git nmap xz-utils
          rm -rf /var/lib/apt/lists/*
      - name: Install Python dependencies
        run: |
          pip install poetry
          poetry install
      - name: Install files in shared volume
        run: |
          tar xJf tests/files/base-files_11.tar.xz -C /tmp
      - name: Check services
        run: nmap fossology -p 80
      - name: Run tests
        run: |
          poetry run coverage run --source=fossology -m pytest tests/test_foss_cli*.py
          poetry run coverage report -m

