name: API Tests

on:
  pull_request:
    paths-ignore:
      - '**cli**'
  push:
    branches:
      - master

jobs:
  test-latest:
    name: Integration Tests (latest Fossology)
    runs-on: ubuntu-latest

    container:
      image: python:3.10-slim
      volumes:
        - /tmp:/tmp

    services:
      fossology:
        image: fossology/fossology:latest
        ports:
          - 8081:80
        volumes:
          - /tmp:/tmp

    steps:
      - uses: actions/checkout@v1
      - name: Install host dependencies
        run: |
          apt-get -qq update
          apt-get install -qq gcc git nmap xz-utils
          rm -rf /var/lib/apt/lists/*
      - name: Install Python dependencies
        run: |
          pip install poetry
          poetry install
      - name: Install files in shared volume
        run: |
          tar xJf tests/files/base-files_11.tar.xz -C /tmp
      - name: Check services
        run: nmap fossology -p 80
      - name: Run tests
        run: |
          export API_LATEST=true
          poetry run coverage run --source=fossology -m pytest
          poetry run coverage report -m
        continue-on-error: true
      - name: upload codecoverage results only if we are on the repository fossology/fossology-python 
        if: ${{ github.repository == 'fossology/fossology-python' }}
        run: poetry run codecov -t ${{ secrets.CODECOV_TOKEN }}
 

  test-last-release:
    name: Integration Tests (Fossology 4.1.0)
    runs-on: ubuntu-latest

    container:
      image: python:3.10-slim
      volumes:
        - /tmp:/tmp

    services:
      fossology:
        image: fossology/fossology:4.1.0
        ports: 
          - 8081:80
        volumes:
          - /tmp:/tmp

    steps:
      - uses: actions/checkout@v1
      - name: Install host dependencies
        run: |
          apt-get -qq update
          apt-get install -qq gcc git nmap xz-utils
          rm -rf /var/lib/apt/lists/*
      - name: Install Python dependencies
        run: |
          pip install poetry
          poetry install
      - name: Install files in shared volume
        run: |
          tar xJf tests/files/base-files_11.tar.xz -C /tmp
      - name: Check services
        run: nmap fossology -p 80
      - name: Run tests
        run: |
          poetry run coverage run --source=fossology -m pytest
          poetry run coverage report -m
      - name: upload codecoverage results only if we are on the repository fossology/fossology-python 
        if: ${{ github.repository == 'fossology/fossology-python' }}
        run: poetry run codecov -t ${{ secrets.CODECOV_TOKEN }}
