name: Static Checks

on:
  push:

jobs:
  test:
    name: Static Checks
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        container:
        - 'python:3.11-slim'
        - 'python:3.12-slim'

    container: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v1
      - name: Install host dependencies
        run: |
          apt-get -qq update
          apt-get install -qq gcc git
          rm -rf /var/lib/apt/lists/*
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with=dev
      - name: Lint using ruff
        run: poetry run ruff check
      - name: Check types with mypy
        run: poetry run poe types
